#!/bin/bash

# Do this to get the ROS_ROBOT_SERIAL_NO envar.
source /etc/ros/setup.bash

# Pass the ROS_ROBOT_SERIAL_NO envar to the base platform computer,
# and restart the adaptor ROS node.
ssh 10.252.252.1 /bin/bash << EOF
   source /opt/clearpath/2.22/setup.bash
   rosnode kill /${ROS_ROBOT_SERIAL_NO}_platform_api_robot_adaptor
EOF
