#!/bin/bash
source /etc/ros/setup.bash
(trap 'kill 0' SIGINT;
  bash $(catkin_find boxer_base scripts/start-platform-bridge --first-only) &
  bash $(catkin_find boxer_base scripts/start-fleet-bridge --first-only) &
  bash $(catkin_find boxer_base scripts/start-autonomy-bridge --first-only) )
